ffwinspool/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
import django.contrib.auth.views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    #path('winspool/', include('winspool.urls',namespace=("winspool", "winspool"))),
    path('winspool/', include(('winspool.urls', 'winspool'), namespace="winspool")),
    #re_path(r'^winspool/login/$', auth_views.LoginView,{'template_name':"winspool/login.html"}),
    #re_path(r'^winspool/logout/$', auth_views.LogoutView,{'next_page': '/winspool/login/'}),
    path('winspool/', include('django.contrib.auth.urls')),
    #re_path(r'^winspool/logout/$', auth_views.LogoutView,{'next_page': '/winspool/login/'}),

]

urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('winspool/', include(('winspool.urls', 'winspool'), namespace="winspool")),
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='main.html'), name='main'),
    path('winspool/login', auth_views.LoginView,{'template_name':"winspool/login.html"}, name='login'),
    path('winspool/logout', auth_views.LogoutView,{'next_page': "winspool/login.html"}),
    #path('winspool/password_reset', auth_views.PasswordResetView,{'template': "registration/password_reset_form.html"}),
    path('winspool/', include('django.contrib.auth.urls')),
]

winspool/urls.py
from django.urls import path

from . import views

urlpatterns = [
    #path('', views.index, name='index'),
    #url(r'^$', views.index, name='index'),
    #url(r'summary/$', view.summary, name='summary')
    #path('', views.index, name='index'),
    path('summary/', views.summary, name='summary'),
    path('details/', views.details, name='details')
]

winspool/models.py
from django.db import models

# Create your models here.
class Player(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    predicted_score = models.FloatField(default=0.0)
    current_score = models.IntegerField(default=0)

    @property
    def teams(self):
        return self.team_set.filter(player=self)

    @property
    def season_score(self):
        score = 0
        for x in self.teams:
            score += x.wins
        return score

    def week_score(self, week):
        score = 0
        for x in self.teams:
            score += x.weekWins(week)
        return score

    def team_week_scores(self, week):
        retval = []
        for t in self.teams:
            retval.append((t.full_name, t.weekWins(week)))
        return retval
        

class Week(models.Model):
    score = models.IntegerField(default=0)
    winning_teams = models.CharField(max_length=11)
    player = models.ForeignKey(Player, on_delete=models.CASCADE)
    week = models.IntegerField(default=0)
    season = models.IntegerField(default=2018)

class Team(models.Model):
    name = models.CharField(max_length=3)
    full_name = models.CharField(max_length=30)
    pick = models.IntegerField()
    #wins = models.IntegerField()
    player = models.ForeignKey(Player, on_delete=models.CASCADE)

    @property
    def wins(self):
        retwins = 0
        weeks = Week.objects.filter(player=self.player)
        for w in weeks:
            #print("Adding scores for week %d with a score of %d for player %s" % (w.week, w.score, w.player.name))
            if self.name in w.winning_teams.split(','):
                #retwins += w.score
                retwins += 1
        return retwins

    def weekWins(self, weeknum):
        weeks = Week.objects.filter(player=self.player).filter(week=weeknum)
        week = None
        if len(weeks) != 0:
            week = weeks[0]
        else:
            return 0
        if self.name in week.winning_teams.split(","):
            return 1
        else:
            return 0

class NFLGame(models.Model):
    home_team = models.CharField(max_length=3)
    away_team = models.CharField(max_length=3)
    game_id = models.IntegerField()
    complete = models.IntegerField(default=0)
    winner = models.CharField(max_length=3)
    week = models.IntegerField(default=0)
    season = models.IntegerField(default=2018)

winspool/views.py
from django.http import HttpResponse
from django.template import Context
from django.shortcuts import render,render_to_response, get_object_or_404
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login
from django.contrib.auth.forms import UserCreationForm,forms
from django.contrib.auth.decorators import login_required
from winspool.models import Player

# Create your views here.
def index(request):
    return render(request, 'winspool/index.html', {})

@login_required
def summary(request):
    retval = []
    players = Player.objects.all()
    for p in players:
        tmpdict = {"player": p}
        teams = p.teams
        tmpdict["team_1"] = teams[0]
        tmpdict["team_2"] = teams[1]
        tmpdict["team_3"] = teams[2]
        retval.append(tmpdict)
    return render(request, 'winspool/summary.html', {"results": retval})

@login_required
def details(request):
    retval = []
    players = Player.objects.all()
    for p in players:
        tmpdict = {"player": p}
        teams = p.teams
        tmpdict["team_1"] = teams[0]
        tmpdict["team_2"] = teams[1]
        tmpdict["team_3"] = teams[2]
        for x in range(17):
            for y in range(3):
                weekwins = teams[y].weekWins(x+1)
                tmpdict["week_%d_%d" % (x+1,y+1)] = weekwins
        retval.append(tmpdict)
    return render(request, 'winspool/summary_details.html', {"results": retval})

winspool/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    {% load bootstrap3 %}
    {% bootstrap_messages %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/tablesorter.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600" rel="stylesheet">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.tablescroll.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/theme.bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-table.css' %}" />

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <script src="{% static 'js/jquery-ui-1.10.0.custom.min.js' %}"></script>
    <script src="{% static 'js/jquery.floatThead.min.js' %}"></script>
    {% bootstrap_javascript %}

    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <title>NFL Wins Pool</title>
    {% block head %}{% endblock %}
</head>

<body>

<nav class="navbar navbar-default" role="navigation">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex1-collapse">
        <span class="icon-bar"></span>
        <i class="icon-cog"></i>
      </button>
      <a class="navbar-brand " href="{% url 'main' %}">
      NFL Wins Pool</a>
    </div>

    {% if user.is_authenticated %}
    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav collapse navbar-collapse navbar-responsive-collapse" id="navbar-ex1-collapse">
        <li class="{% block link_summary_class %}{% endblock %}">
          <a href="{% url 'winspool:summary' %}">
            <i class="fa fa-bolt"></i>
            <span>Summary</span>
          </a>
        </li>
        <li class="{% block link_summarydetail_class %}{% endblock %}">
          <a href="{% url 'winspool:details' %}">
            <i class="fa fa-bolt"></i>
            <span>Details</span>
          </a>
        </li>
      </ul>
      {% endif %}

      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
          <p class="navbar-text">Signed in as {{ user.get_username }}</p>
        </li>
        <li>
          <a href="{% url 'logout' %}">
            <i class="fa fa-cog"></i> Logout
          </a>
        </li>
        {% else %}
        <li class="">
          <a href="{% url 'login' %}">
            <i class="fa fa-cog"></i>
            <span>Login</span>
          </a>
        </li>
        {% endif %}
      </ul>

    <!--</div>&lt;!&ndash; /.navbar-collapse &ndash;&gt;-->
  </div> <!-- /.container -->
</nav>

<div class="container">
  <div class="row">
    <div class="col-sm-12">
      {% block result_content %}
      {% endblock %}
    </div>
  </div>
</div>

<footer>
  <div class="row">

    <div id="footer-terms" class="col-md-12 text-center">
    Theme by <a href="{% url 'main' %}" target="_blank">NFL Wins Pool</a>
    </div> <!-- /.span6 -->

  </div> <!-- /row -->
  <div class="row">

    <div id="footer-copyright" class="col-md-12 text-center">
      &copy; NFL Wins Pool
    </div> <!-- /span6 -->

  </div>
</footer>

<!-- Placed at the end of the document so the pages load faster -->

<script src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.pie.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/flot/0.8.2/jquery.flot.resize.min.js"></script>

<script src="{% static 'js/Application.js' %}"></script>
<script src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
<!-- <script src="{% static 'js/jquery.tablesorter.widgets.js' %}"></script> -->


  </body>
</html>

winspool/templates/index.html
{% extends "base.html" %}
{% block content %}

{% if user.is_authenticated %}

<p> Welcome {{ user.username }}

{% else %}

<a href="{% url 'django.contrib.auth.views.LoginView' %}">Please Login</a><br>
Not Yet a User?

{% endif %}

{% endblock %}

winspool/templates/login.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% bootstrap_messages %}

{% block content %}

<div class="container">

  <div class="row">
    <div class="col-sm-12">
      {% if form.errors %}
      <p>Your username and password didn't match. Please try again.</p>
      {% endif %}
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">

          <form class="form form-horizontal" method="post" action="{% url 'django.contrib.auth.views.LoginView' %}">
            {% csrf_token %}
            {% bootstrap_form form layout="horizontal" %}

            <div class="form-group">
              <div class="col-xs-offset-1 col-xs-3">
                <a class="btn btn-link" href="{% url 'django.contrib.auth.views.PasswordResetView' %}?">
                  Forgot Password?
                </a>
              </div>
              <div class="col-xs-offset-9">
                <button type="submit" class="btn btn-primary">Login</button>
              </div>
            </div>
            <input type="hidden" name="next" value="{{ next }}" />
          </form>

        </div>
      </div>

    </div>
  </div>




</div>
{% endblock %}

winspool/templates/main.html
{% extends "base.html" %}

{% load staticfiles %}

{% block result_content %}

<div class="container">
  <div class="well main-panel">
    <div class="content">
      <div class="row">
        <div class="col-xs-6">
          <h2>2018 NFL Wins Pool</h2>
        </div>
      </div>
      <h3> Talk to Alex or Jeff for user logins if you don't have one. </h3>
    </div>
  </div>
</div>
{% endblock %}

winspool/templates/summary_new.html
{% extends "weeklyresultsmain.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
<script type="text/javascript">
        $(document).ready(function()
            {
                $("#results-table").tablesorter({sortList: [[1,1]]});
            }
        );

</script>

{% endblock %}

{% block link_weeklyresults_class %}<li class="active">{% endblock %}

{% block week_intro %}{% endblock %}

{% block btn_text %} Week {{week}} {% endblock %}

{% block result_content %}
  {% if ok %}
    <!--<div class="col-sm-8">-->
      <table id="results-table" class="table table-striped table-condensed sorter-bootstrap">
        <thead>
        <tr>
          <th></th>
          <th></th>
          <th colspan="2" class="text-center deemphasis">Quarterback</th>
          <th colspan="2" class="text-center deemphasis">Running back</th>
          <th colspan="2" class="text-center deemphasis">Wide Receiver</th>
          <th colspan="2" class="text-center deemphasis">Tight End</th>
        </tr>
        <tr>
          <th>User</th>
          <th>Score</th>
          <th>Name</th>
          <th>Score</th>
          <th>Name</th>
          <th>Score</th>
          <th>Name</th>
          <th>Score</th>
          <th>Name</th>
          <th>Score</th>
        </tr>
        </thead>
        <tbody>
        {% for pick in picks %}
        <tr>
          <td><em>{{pick.user}}</em></td>
          <td><strong>{{pick.score}}</strong></td>
          <td>{{pick.qbName}}</td>
          <td>{{pick.qbScore}}</td>
          <td>{{pick.rbName}}</td>
          <td>{{pick.rbScore}}</td>
          <td>{{pick.wrName}}</td>
          <td>{{pick.wrScore}}</td>
          <td>{{pick.teName}}</td>
          <td>{{pick.teScore}}</td>
        </tr>
        {% endfor %}
        </tbody>
      </table>
    <!--</div>-->
  {% else %}
    <p> Not all games have started yet.  Come back later to see the results! </p>
  {% endif %}
{% endblock %}

winspool/templates/winspool/summary.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
<script type="text/javascript">
        $(document).ready(function()
            {
                $("#results-table").tablesorter({sortList: [[1,1]]});
            }
        );

</script>

{% endblock %}

{% block link_summary_class %}"active"{% endblock %}

{% block result_content %}
      <table id="results-table" class="table table-striped table-condensed sorter-bootstrap"> 
        <thead>
          <tr>
            <th class="sorter-text">Person<i class="fa fa-fw fa-sort"></i></th>
            <th class="sorter-text">Total Wins<i class="fa fa-fw fa-sort"></i></th>
            <th data-sorter="false">Pick Number</th>
            <th data-sorter="false">Team</th>
            <th data-sorter="false">Team Wins</th>
          </tr>
        </thead>
        <tbody>
        {% for value in results %}
          <tr>
            <td rowspan="3"><em>{{value.player.name}}</em></td>
            <td rowspan="3"><strong>{{value.player.season_score}}</strong></td>
            <td>{{value.team_1.pick}}</td>
            <td>{{value.team_1.full_name}}</td>
            <td>{{value.team_1.wins}}</td>
          </tr> 
          <tr class="tablesorter-childRow">
            <td>{{value.team_2.pick}}</td>
            <td>{{value.team_2.full_name}}</td>
            <td>{{value.team_2.wins}}</td>
          </tr>
          <tr class="tablesorter-childRow">
            <td>{{value.team_3.pick}}</td>
            <td>{{value.team_3.full_name}}</td>
            <td>{{value.team_3.wins}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock %}

winspool/templates/winspool/summary_details.html
{% extends "base.html" %}

{% load static %}

{% block head %}
<script type="text/javascript" src="{% static 'js/jquery.tablesorter.min.js' %}"></script>
<script type="text/javascript">
        $(document).ready(function()
            {
                $("#results-table").tablesorter({sortList: [[1,1]]});
            }
        );

</script>

{% endblock %}

{% block link_summarydetail_class %}"active"{% endblock %}

{% block result_content %}
      <table id="results-table" class="table table-striped table-condensed sorter-bootstrap"> 
        <thead>
          <tr>
            <th class="sorter-text">Person<i class="fa fa-fw fa-sort"></i></th>
            <th class="sorter-text">Total Wins<i class="fa fa-fw fa-sort"></i></th>
            <th data-sorter="false">Pick Number</th>
            <th data-sorter="false">Team</th>
            <th data-sorter="false">Team Wins</th>
            <th data-sorter="false">Week 1</th>
            <th data-sorter="false">Week 2</th>
            <th data-sorter="false">Week 3</th>
            <th data-sorter="false">Week 4</th>
            <th data-sorter="false">Week 5</th>
            <th data-sorter="false">Week 6</th>
            <th data-sorter="false">Week 7</th>
            <th data-sorter="false">Week 8</th>
            <th data-sorter="false">Week 9</th>
            <th data-sorter="false">Week 10</th>
            <th data-sorter="false">Week 11</th>
            <th data-sorter="false">Week 12</th>
            <th data-sorter="false">Week 13</th>
            <th data-sorter="false">Week 14</th>
            <th data-sorter="false">Week 15</th>
            <th data-sorter="false">Week 16</th>
            <th data-sorter="false">Week 17</th>
          </tr>
        </thead>
        <tbody>
        {% for value in results %}
          <tr>
            <td rowspan="3"><em>{{value.player.name}}</em></td>
            <td rowspan="3"><strong>{{value.player.season_score}}</strong></td>
            <td>{{value.team_1.pick}}</td>
            <td>{{value.team_1.name}}</td>
            <td>{{value.team_1.wins}}</td>
            <td>{{value.week_1_1}}</td>
            <td>{{value.week_2_1}}</td>
            <td>{{value.week_3_1}}</td>
            <td>{{value.week_4_1}}</td>
            <td>{{value.week_5_1}}</td>
            <td>{{value.week_6_1}}</td>
            <td>{{value.week_7_1}}</td>
            <td>{{value.week_8_1}}</td>
            <td>{{value.week_9_1}}</td>
            <td>{{value.week_10_1}}</td>
            <td>{{value.week_11_1}}</td>
            <td>{{value.week_12_1}}</td>
            <td>{{value.week_13_1}}</td>
            <td>{{value.week_14_1}}</td>
            <td>{{value.week_15_1}}</td>
            <td>{{value.week_16_1}}</td>
            <td>{{value.week_17_1}}</td>
          </tr> 
          <tr class="tablesorter-childRow">
            <td>{{value.team_2.pick}}</td>
            <td>{{value.team_2.name}}</td>
            <td>{{value.team_2.wins}}</td>
            <td>{{value.week_1_2}}</td>
            <td>{{value.week_2_2}}</td>
            <td>{{value.week_3_2}}</td>
            <td>{{value.week_4_2}}</td>
            <td>{{value.week_5_2}}</td>
            <td>{{value.week_6_2}}</td>
            <td>{{value.week_7_2}}</td>
            <td>{{value.week_8_2}}</td>
            <td>{{value.week_9_2}}</td>
            <td>{{value.week_10_2}}</td>
            <td>{{value.week_11_2}}</td>
            <td>{{value.week_12_2}}</td>
            <td>{{value.week_13_2}}</td>
            <td>{{value.week_14_2}}</td>
            <td>{{value.week_15_2}}</td>
            <td>{{value.week_16_2}}</td>
            <td>{{value.week_17_2}}</td>
          </tr>
          <tr class="tablesorter-childRow">
            <td>{{value.team_3.pick}}</td>
            <td>{{value.team_3.name}}</td>
            <td>{{value.team_3.wins}}</td>
            <td>{{value.week_1_3}}</td>
            <td>{{value.week_2_3}}</td>
            <td>{{value.week_3_3}}</td>
            <td>{{value.week_4_3}}</td>
            <td>{{value.week_5_3}}</td>
            <td>{{value.week_6_3}}</td>
            <td>{{value.week_7_3}}</td>
            <td>{{value.week_8_3}}</td>
            <td>{{value.week_9_3}}</td>
            <td>{{value.week_10_3}}</td>
            <td>{{value.week_11_3}}</td>
            <td>{{value.week_12_3}}</td>
            <td>{{value.week_13_3}}</td>
            <td>{{value.week_14_3}}</td>
            <td>{{value.week_15_3}}</td>
            <td>{{value.week_16_3}}</td>
            <td>{{value.week_17_3}}</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
{% endblock %}